In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
import os
import sys

In [5]:
sys.path.append("..")

In [6]:
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
players = pd.read_csv("../data/eplplayers20182019stats.csv")

In [30]:
players.head()

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Cresswell,32,629712000,1989/12/15,Premier League,2018/2019,Defender,West Ham United,1589,888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron Lennon,35,545554800,1987/04/16,Premier League,2018/2019,Midfielder,Burnley,1217,487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron Mooy,32,653382000,1990/09/15,Premier League,2018/2019,Midfielder,Huddersfield Town,2327,1190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aaron Ramsey,31,662198400,1990/12/26,Premier League,2018/2019,Midfielder,Arsenal,1327,689,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aaron Rowe,22,968310000,2000/09/07,Premier League,2018/2019,Forward,Huddersfield Town,69,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
players[["full_name","Current Club"]]

                  full_name            Current Club
0           Aaron Cresswell         West Ham United
1              Aaron Lennon                 Burnley
2                Aaron Mooy       Huddersfield Town
3              Aaron Ramsey                 Arsenal
4                Aaron Rowe       Huddersfield Town
..                      ...                     ...
565         Youri Tielemans          Leicester City
566           Yves Bissouma  Brighton & Hove Albion
567        Zechariah Medley                 Arsenal
568  Zeze  Steven Sessegnon                  Fulham
569        Łukasz Fabiański         West Ham United

[570 rows x 2 columns]

In [32]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Columns: 277 entries, full_name to annual_salary_usd
dtypes: float64(237), int64(33), object(7)
memory usage: 1.2+ MB

In [33]:
list(players.columns)

['full_name',
 'age',
 'birthday',
 'birthday_GMT',
 'league',
 'season',
 'position',
 'Current Club',
 'minutes_played_overall',
 'minutes_played_home',
 'minutes_played_away',
 'nationality',
 'appearances_overall',
 'appearances_home',
 'appearances_away',
 'goals_overall',
 'goals_home',
 'goals_away',
 'assists_overall',
 'assists_home',
 'assists_away',
 'penalty_goals',
 'penalty_misses',
 'clean_sheets_overall',
 'clean_sheets_home',
 'clean_sheets_away',
 'conceded_overall',
 'conceded_home',
 'conceded_away',
 'yellow_cards_overall',
 'red_cards_overall',
 'goals_involved_per_90_overall',
 'assists_per_90_overall',
 'goals_per_90_overall',
 'goals_per_90_home',
 'goals_per_90_away',
 'min_per_goal_overall',
 'conceded_per_90_overall',
 'min_per_conceded_overall',
 'min_per_match',
 'min_per_card_overall',
 'min_per_assist_overall',
 'cards_per_90_overall',
 'rank_in_league_top_attackers',
 'rank_in_league_top_midfielders',
 'rank_in_league_top_defenders',
 'rank_in_club_top_scorer',
 'average_rating_overall',
 'assists_per_game_overall',
 'sm_assists_total_overall',
 'assists_per90_percentile_overall',
 'passes_per_90_overall',
 'passes_per_game_overall',
 'passes_per90_percentile_overall',
 'passes_total_overall',
 'passes_completed_per_game_overall',
 'passes_completed_total_overall',
 'pass_completion_rate_percentile_overall',
 'passes_completed_per_90_overall',
 'passes_completed_per90_percentile_overall',
 'short_passes_per_game_overall',
 'long_passes_per_game_overall',
 'key_passes_per_game_overall',
 'key_passes_total_overall',
 'through_passes_per_game_overall',
 'crosses_per_game_overall',
 'tackles_per_90_overall',
 'tackles_per_game_overall',
 'tackles_total_overall',
 'tackles_successful_per_game_overall',
 'dispossesed_per_game_overall',
 'possession_regained_per_game_overall',
 'pressures_per_game_overall',
 'saves_per_game_overall',
 'interceptions_per_game_overall',
 'dribbles_successful_per_game_overall',
 'shots_faced_per_game_overall',
 'shots_per_goal_scored_overall',
 'shots_per_90_overall',
 'shots_off_target_per_game_overall',
 'dribbles_per_game_overall',
 'distance_travelled_per_game_overall',
 'shots_on_target_per_game_overall',
 'xg_per_game_overall',
 'chances_created_per_game_overall',
 'aerial_duels_won_per_game_overall',
 'aerial_duels_per_game_overall',
 'possession_regained_per_90_overall',
 'possession_regained_total_overall',
 'possession_regained_per90_percentile_overall',
 'additional_info',
 'shots_total_overall',
 'shots_per_game_overall',
 'shots_per90_percentile_overall',
 'shots_on_target_total_overall',
 'shots_on_target_per_90_overall',
 'shots_on_target_per90_percentile_overall',
 'shots_off_target_total_overall',
 'shots_off_target_per_90_overall',
 'shots_off_target_per90_percentile_overall',
 'games_subbed_out',
 'games_subbed_in',
 'games_started',
 'tackles_per90_percentile_overall',
 'tackles_successful_per_90_overall',
 'tackles_successful_per90_percentile_overall',
 'tackles_successful_total_overall',
 'interceptions_total_overall',
 'interceptions_per_90_overall',
 'interceptions_per90_percentile_overall',
 'crosses_total_overall',
 'cross_completion_rate_percentile_overall',
 'crosses_per_90_overall',
 'crosses_per90_percentile_overall',
 'through_passes_total_overall',
 'through_passes_per_90_overall',
 'through_passes_per90_percentile_overall',
 'long_passes_total_overall',
 'long_passes_per_90_overall',
 'long_passes_per90_percentile_overall',
 'short_passes_total_overall',
 'short_passes_per_90_overall',
 'short_passes_per90_percentile_overall',
 'key_passes_per_90_overall',
 'key_passes_per90_percentile_overall',
 'dribbles_total_overall',
 'dribbles_per_90_overall',
 'dribbles_per90_percentile_overall',
 'dribbles_successful_total_overall',
 'dribbles_successful_per_90_overall',
 'dribbles_successful_percentage_overall',
 'chances_created_total_overall',
 'chances_created_per_90_overall',
 'chances_created_per90_percentile_overall',
 'saves_total_overall',
 'save_percentage_percentile_overall',
 'saves_per_90_overall',
 'saves_per90_percentile_overall',
 'shots_faced_total_overall',
 'shots_per_goal_conceded_overall',
 'sm_goals_conceded_total_overall',
 'conceded_per90_percentile_overall',
 'shots_faced_per_90_overall',
 'shots_faced_per90_percentile_overall',
 'xg_faced_per_90_overall',
 'xg_faced_per90_percentile_overall',
 'xg_faced_per_game_overall',
 'xg_faced_total_overall',
 'save_percentage_overall',
 'pressures_total_overall',
 'pressures_per_90_overall',
 'pressures_per90_percentile_overall',
 'xg_total_overall',
 'market_value',
 'market_value_percentile',
 'pass_completion_rate_overall',
 'shot_accuraccy_percentage_overall',
 'shot_accuraccy_percentage_percentile_overall',
 'sm_goals_scored_total_overall',
 'dribbled_past_per90_percentile_overall',
 'dribbled_past_per_game_overall',
 'dribbled_past_per_90_overall',
 'dribbled_past_total_overall',
 'dribbles_successful_per90_percentile_overall',
 'dribbles_successful_percentage_percentile_overall',
 'pen_scored_total_overall',
 'pen_missed_total_overall',
 'inside_box_saves_total_overall',
 'blocks_per_game_overall',
 'blocks_per_90_overall',
 'blocks_total_overall',
 'blocks_per90_percentile_overall',
 'ratings_total_overall',
 'clearances_per_game_overall',
 'clearances_per_90_overall',
 'clearances_total_overall',
 'pen_committed_total_overall',
 'pen_save_percentage_overall',
 'pen_committed_per_90_overall',
 'pen_committed_per90_percentile_overall',
 'pen_committed_per_game_overall',
 'pens_saved_total_overall',
 'pens_taken_total_overall',
 'hit_woodwork_total_overall',
 'hit_woodwork_per_game_overall',
 'hit_woodwork_per_90_overall',
 'punches_total_overall',
 'punches_per_game_overall',
 'punches_per_90_overall',
 'offsides_per_90_overall',
 'offsides_per_game_overall',
 'offsides_total_overall',
 'penalties_won_total_overall',
 'shot_conversion_rate_overall',
 'shot_conversion_rate_percentile_overall',
 'sm_minutes_played_per90_percentile_overall',
 'sm_minutes_played_recorded_overall',
 'minutes_played_percentile_overall',
 'matches_played_percentile_overall',
 'min_per_goal_percentile_overall',
 'min_per_conceded_percentile_overall',
 'xa_total_overall',
 'xa_per90_percentile_overall',
 'xa_per_game_overall',
 'xa_per_90_overall',
 'npxg_total_overall',
 'npxg_per90_percentile_overall',
 'npxg_per_game_overall',
 'npxg_per_90_overall',
 'fouls_drawn_per90_percentile_overall',
 'fouls_drawn_total_overall',
 'fouls_drawn_per_game_overall',
 'fouls_drawn_per_90_overall',
 'fouls_committed_per_90_overall',
 'fouls_committed_per_game_overall',
 'fouls_committed_per90_percentile_overall',
 'fouls_committed_total_overall',
 'xg_per_90_overall',
 'xg_per90_percentile_overall',
 'average_rating_percentile_overall',
 'clearances_per90_percentile_overall',
 'hit_woodwork_per90_percentile_overall',
 'punches_per90_percentile_overall',
 'offsides_per90_percentile_overall',
 'aerial_duels_won_per90_percentile_overall',
 'aerial_duels_total_overall',
 'aerial_duels_per_90_overall',
 'aerial_duels_per90_percentile_overall',
 'aerial_duels_won_total_overall',
 'aerial_duels_won_percentage_overall',
 'aerial_duels_won_per_90_overall',
 'duels_per_90_overall',
 'duels_per_game_overall',
 'duels_total_overall',
 'duels_won_total_overall',
 'duels_won_per90_percentile_overall',
 'duels_per90_percentile_overall',
 'duels_won_per_90_overall',
 'duels_won_per_game_overall',
 'duels_won_percentage_overall',
 'dispossesed_total_overall',
 'dispossesed_per_90_overall',
 'dispossesed_per90_percentile_overall',
 'progressive_passes_total_overall',
 'cross_completion_rate_overall',
 'distance_travelled_total_overall',
 'distance_travelled_per_90_overall',
 'distance_travelled_per90_percentile_overall',
 'accurate_crosses_total_overall',
 'accurate_crosses_per_game_overall',
 'accurate_crosses_per_90_overall',
 'accurate_crosses_per90_percentile_overall',
 'sm_matches_recorded_total_overall',
 'games_started_percentile_overall',
 'games_subbed_in_percentile_overall',
 'games_subbed_out_percentile_overall',
 'hattricks_total_overall',
 'two_goals_in_a_game_total_overall',
 'three_goals_in_a_game_total_overall',
 'two_goals_in_a_game_percentage_overall',
 'three_goals_in_a_game_percentage_overall',
 'goals_involved_per90_percentile_overall',
 'goals_per90_percentile_overall',
 'goals_per90_percentile_away',
 'goals_per90_percentile_home',
 'man_of_the_match_total_overall',
 'annual_salary_eur',
 'annual_salary_eur_percentile',
 'clean_sheets_percentage_percentile_overall',
 'min_per_card_percentile_overall',
 'cards_per90_percentile_overall',
 'booked_over05_overall',
 'booked_over05_percentage_overall',
 'booked_over05_percentage_percentile_overall',
 'shirt_number',
 'annual_salary_gbp',
 'annual_salary_usd']

In [19]:
matches = pd.read_csv("../data/eplmatches20182019.csv")

In [20]:
matches.head()

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1533927600,Aug 10 2018 - 7:00pm,complete,74439,Manchester United,Leicester City,Andre Marriner,1,0.0,0.0,...,1.37,4.98,9.81,1.33,2.00,3.60,7.50,2.05,1.69,Old Trafford (Manchester)
1,1533987000,Aug 11 2018 - 11:30am,complete,51749,Newcastle United,Tottenham Hotspur,Martin Atkinson,1,0.0,0.0,...,4.51,3.77,1.84,1.31,1.95,3.50,5.75,1.83,1.87,St. James' Park (Newcastle upon Tyne)
2,1533996000,Aug 11 2018 - 2:00pm,complete,10353,AFC Bournemouth,Cardiff City,Kevin Friend,1,0.0,0.0,...,2.03,3.51,3.96,1.31,1.95,3.45,6.70,1.83,1.83,Vitality Stadium (Bournemouth- Dorset)
3,1533996000,Aug 11 2018 - 2:00pm,complete,24821,Fulham,Crystal Palace,Mike Dean,1,0.0,0.0,...,2.31,3.44,3.26,1.28,1.87,3.20,7.00,1.71,2.00,Craven Cottage (London)
4,1533996000,Aug 11 2018 - 2:00pm,complete,24121,Huddersfield Town,Chelsea,Chris Kavanagh,1,0.0,0.0,...,7.47,4.27,1.51,1.29,1.91,3.30,6.95,2.00,1.71,John Smith's Stadium (Huddersfield- West Yorkshire)

In [22]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 66 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   timestamp                            380 non-null    int64
 1   date_GMT                             380 non-null    object
 2   status                               380 non-null    object
 3   attendance                           380 non-null    int64
 4   home_team_name                       380 non-null    object
 5   away_team_name                       380 non-null    object
 6   referee                              380 non-null    object
 7   Game Week                            380 non-null    int64
 8   Pre-Match PPG (Home)                 380 non-null    float64
 9   Pre-Match PPG (Away)                 380 non-null    float64
 10  home_ppg                             380 non-null    float64
 11  away_ppg                             380 non-null    float64
 12  home_team_goal_count                 380 non-null    int64
 13  away_team_goal_count                 380 non-null    int64
 14  total_goal_count                     380 non-null    int64
 15  total_goals_at_half_time             380 non-null    int64
 16  home_team_goal_count_half_time       380 non-null    int64
 17  away_team_goal_count_half_time       380 non-null    int64
 18  home_team_goal_timings               292 non-null    object
 19  away_team_goal_timings               261 non-null    object
 20  home_team_corner_count               380 non-null    int64
 21  away_team_corner_count               380 non-null    int64
 22  home_team_yellow_cards               380 non-null    int64
 23  home_team_red_cards                  380 non-null    int64
 24  away_team_yellow_cards               380 non-null    int64
 25  away_team_red_cards                  380 non-null    int64
 26  home_team_first_half_cards           380 non-null    int64
 27  home_team_second_half_cards          380 non-null    int64
 28  away_team_first_half_cards           380 non-null    int64
 29  away_team_second_half_cards          380 non-null    int64
 30  home_team_shots                      380 non-null    int64
 31  away_team_shots                      380 non-null    int64
 32  home_team_shots_on_target            380 non-null    int64
 33  away_team_shots_on_target            380 non-null    int64
 34  home_team_shots_off_target           380 non-null    int64
 35  away_team_shots_off_target           380 non-null    int64
 36  home_team_fouls                      380 non-null    int64
 37  away_team_fouls                      380 non-null    int64
 38  home_team_possession                 380 non-null    int64
 39  away_team_possession                 380 non-null    int64
 40  Home Team Pre-Match xG               380 non-null    float64
 41  Away Team Pre-Match xG               380 non-null    float64
 42  team_a_xg                            380 non-null    float64
 43  team_b_xg                            380 non-null    float64
 44  average_goals_per_match_pre_match    380 non-null    float64
 45  btts_percentage_pre_match            380 non-null    int64
 46  over_15_percentage_pre_match         380 non-null    int64
 47  over_25_percentage_pre_match         380 non-null    int64
 48  over_35_percentage_pre_match         380 non-null    int64
 49  over_45_percentage_pre_match         380 non-null    int64
 50  over_15_HT_FHG_percentage_pre_match  380 non-null    int64
 51  over_05_HT_FHG_percentage_pre_match  380 non-null    int64
 52  over_15_2HG_percentage_pre_match     380 non-null    int64
 53  over_05_2HG_percentage_pre_match     380 non-null    int64
 54  average_corners_per_match_pre_match  380 non-null    float64
 55  average_cards_per_match_pre_match    380 non-null    float64
 56  odds_ft_home_team_win                380 non-null    float64
 57  odds_ft_draw                         380 non-null    float64
 58  odds_ft_away_team_win                380 non-null    float64
 59  odds_ft_over15                       380 non-null    float64
 60  odds_ft_over25                       380 non-null    float64
 61  odds_ft_over35                       380 non-null    float64
 62  odds_ft_over45                       380 non-null    float64
 63  odds_btts_yes                        380 non-null    float64
 64  odds_btts_no                         380 non-null    float64
 65  stadium_name                         380 non-null    object
dtypes: float64(20), int64(38), object(8)
memory usage: 196.1+ KB

In [30]:
matches[["home_team_name","away_team_name", "home_team_goal_count", "away_team_goal_count"]]

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count
0,Manchester United,Leicester City,2,1
1,Newcastle United,Tottenham Hotspur,1,2
2,AFC Bournemouth,Cardiff City,2,0
3,Fulham,Crystal Palace,0,2
4,Huddersfield Town,Chelsea,0,3
...,...,...,...,...
375,Liverpool,Wolverhampton Wanderers,2,0
376,Manchester United,Cardiff City,0,2
377,Southampton,Huddersfield Town,1,1
378,Tottenham Hotspur,Everton,2,2
379,Watford,West Ham United,1,4

In [44]:
#number of unique teams
np.unique(matches[["home_team_name"]].values)

array(['AFC Bournemouth', 'Arsenal', 'Brighton & Hove Albion', 'Burnley',
       'Cardiff City', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham',
       'Huddersfield Town', 'Leicester City', 'Liverpool',
       'Manchester City', 'Manchester United', 'Newcastle United',
       'Southampton', 'Tottenham Hotspur', 'Watford', 'West Ham United',
       'Wolverhampton Wanderers'], dtype=object)

In [45]:
matches[["home_team_name"]].nunique()

home_team_name    20
dtype: int64

In [34]:
teamPlayers = players[["full_name","Current Club"]].sort_values(by="Current Club").groupby("Current Club").count()

In [35]:
teamPlayers.reset_index(inplace=True)
del teamPlayers["full_name"]
teamPlayers

               Current Club
0           AFC Bournemouth
1                   Arsenal
2    Brighton & Hove Albion
3                   Burnley
4              Cardiff City
5                   Chelsea
6            Crystal Palace
7                   Everton
8                    Fulham
9         Huddersfield Town
10           Leicester City
11                Liverpool
12          Manchester City
13        Manchester United
14         Newcastle United
15              Southampton
16        Tottenham Hotspur
17                  Watford
18          West Ham United
19  Wolverhampton Wanderers

In [36]:
playerminutes = players[["full_name","Current Club", "position","minutes_played_overall"]
][players["minutes_played_overall"]>500].sort_values(by="minutes_played_overall", ascending=False)
playerminutes

,full_name,Current Club,position,minutes_played_overall
569,Łukasz Fabiański,West Ham United,Goalkeeper,3420
76,Ben Mee,Burnley,Defender,3420
426,Neil Leonard Dula Etheridge,Cardiff City,Goalkeeper,3420
144,David de Gea,Manchester United,Goalkeeper,3420
36,Alisson Becker,Liverpool,Goalkeeper,3420
...,...,...,...,...
276,Joel Ward,Crystal Palace,Defender,551
413,Moussa Dembele,Tottenham Hotspur,Midfielder,516
564,Yoshinori Muto,Newcastle United,Forward,516
320,Kevin Long,Burnley,Defender,513
546,Victor Wanyama,Tottenham Hotspur,Midfielder,509

In [37]:
goalkeeper = playerminutes[playerminutes["position"]=="Goalkeeper"]

In [38]:
# check how many goalkeepers are there per team
goalkeeper.groupby("Current Club").count()

                         full_name  position  minutes_played_overall
Current Club
AFC Bournemouth                  2         2                       2
Arsenal                          2         2                       2
Brighton & Hove Albion           1         1                       1
Burnley                          2         2                       2
Cardiff City                     1         1                       1
Chelsea                          1         1                       1
Crystal Palace                   2         2                       2
Everton                          1         1                       1
Fulham                           2         2                       2
Huddersfield Town                2         2                       2
Leicester City                   1         1                       1
Liverpool                        1         1                       1
Manchester City                  1         1                       1
Manchester United                1         1                       1
Newcastle United                 1         1                       1
Southampton                      2         2                       2
Tottenham Hotspur                1         1                       1
Watford                          1         1                       1
West Ham United                  1         1                       1
Wolverhampton Wanderers          1         1                       1

In [39]:
#get only the first goalkeeper
goalkeeper = goalkeeper.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
goalkeeper

,full_name,Current Club,position,minutes_played_overall
569,Łukasz Fabiański,West Ham United,Goalkeeper,3420
426,Neil Leonard Dula Etheridge,Cardiff City,Goalkeeper,3420
144,David de Gea,Manchester United,Goalkeeper,3420
36,Alisson Becker,Liverpool,Goalkeeper,3420
290,Jordan Pickford,Everton,Goalkeeper,3420
168,Ederson,Manchester City,Goalkeeper,3420
72,Ben Foster,Watford,Goalkeeper,3420
311,Kasper Schmeichel,Leicester City,Goalkeeper,3420
376,Martin Dúbravka,Newcastle United,Goalkeeper,3420
478,Rui Patrício,Wolverhampton Wanderers,Goalkeeper,3330
318,Kepa Arrizabalaga,Chelsea,Goalkeeper,3240
383,Mathew Ryan,Brighton & Hove Albion,Goalkeeper,3060
225,Hugo Lloris,Tottenham Hotspur,Goalkeeper,2970
84,Bernd Leno,Arsenal,Goalkeeper,2835
281,Jonas Lössl,Huddersfield Town,Goalkeeper,2777
503,Sergio Rico,Fulham,Goalkeeper,2610
23,Alex McCarthy,Southampton,Goalkeeper,2250
66,Asmir Begović,AFC Bournemouth,Goalkeeper,2160
541,Vicente Guaita,Crystal Palace,Goalkeeper,1755
534,Tom Heaton,Burnley,Goalkeeper,1710

In [40]:
forward = playerminutes[playerminutes["position"]=="Forward"]
forward

,full_name,Current Club,position,minutes_played_overall
21,Aleksandar Mitrović,Fulham,Forward,3282
410,Mohamed Salah,Liverpool,Forward,3262
460,Raúl Jiménez,Wolverhampton Wanderers,Forward,3124
487,Sadio Mané,Liverpool,Forward,3086
300,Joshua King,AFC Bournemouth,Forward,2974
...,...,...,...,...
190,Fernando Llorente Torres,Tottenham Hotspur,Forward,683
15,Ademola Lookman,Everton,Forward,601
295,Joselu,Newcastle United,Forward,586
13,Adama Diakhaby,Huddersfield Town,Forward,551
564,Yoshinori Muto,Newcastle United,Forward,516

In [41]:
#get only the first forward
forward = forward.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
forward

,full_name,Current Club,position,minutes_played_overall
21,Aleksandar Mitrović,Fulham,Forward,3282
410,Mohamed Salah,Liverpool,Forward,3262
460,Raúl Jiménez,Wolverhampton Wanderers,Forward,3124
300,Joshua King,AFC Bournemouth,Forward,2974
68,Ayoze Perez,Newcastle United,Forward,2929
470,Roberto Pereyra,Watford,Forward,2825
457,Raheem Sterling,Manchester City,Forward,2777
250,Jamie Vardy,Leicester City,Forward,2735
453,Pierre-Emerick Aubameyang,Arsenal,Forward,2731
463,Richarlison,Everton,Forward,2679
111,Chris Wood,Burnley,Forward,2582
207,Glenn Murray,Brighton & Hove Albion,Forward,2513
215,Harry Kane,Tottenham Hotspur,Forward,2427
369,Marcus Rashford,Manchester United,Forward,2362
145,David Junior Hoilett,Cardiff City,Forward,2142
558,Willian,Chelsea,Forward,2108
373,Marko Arnautović,West Ham United,Forward,2000
519,Steve Mounié,Huddersfield Town,Forward,1777
135,Danny Ings,Southampton,Forward,1668
288,Jordan Ayew,Crystal Palace,Forward,1186

In [42]:
mid1 = playerminutes[playerminutes["position"]=="Midfielder"]
mid1

,full_name,Current Club,position,minutes_played_overall
122,Conor Coady,Wolverhampton Wanderers,Midfielder,3420
354,Luka Milivojević,Crystal Palace,Midfielder,3420
234,Jack Cork,Burnley,Midfielder,3313
554,Wilfred Ndidi,Leicester City,Midfielder,3299
421,Nathan Redmond,Southampton,Midfielder,3276
...,...,...,...,...
213,Hamza Choudhury,Leicester City,Midfielder,596
44,Andreas Pereira,Manchester United,Midfielder,595
336,Leandro Bacuna,Cardiff City,Midfielder,554
413,Moussa Dembele,Tottenham Hotspur,Midfielder,516
546,Victor Wanyama,Tottenham Hotspur,Midfielder,509

In [43]:
#get only the first midfielder
mid1 = mid1.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
mid1

,full_name,Current Club,position,minutes_played_overall
122,Conor Coady,Wolverhampton Wanderers,Midfielder,3420
354,Luka Milivojević,Crystal Palace,Midfielder,3420
234,Jack Cork,Burnley,Midfielder,3313
554,Wilfred Ndidi,Leicester City,Midfielder,3299
421,Nathan Redmond,Southampton,Midfielder,3276
481,Ryan Fraser,AFC Bournemouth,Midfielder,3173
292,Jorginho,Chelsea,Midfielder,3165
212,Gylfi Sigurdsson,Everton,Midfielder,3134
7,Abdoulaye Doucouré,Watford,Midfielder,3062
188,Felipe Anderson,West Ham United,Midfielder,3054
441,Paul Pogba,Manchester United,Midfielder,3011
387,Matt Ritchie,Newcastle United,Midfielder,2940
83,Bernardo Silva,Manchester City,Midfielder,2853
114,Christian Eriksen,Tottenham Hotspur,Midfielder,2772
205,Georginio Wijnaldum,Liverpool,Midfielder,2735
543,Víctor Camarasa,Cardiff City,Midfielder,2579
150,Davy Pröpper,Brighton & Hove Albion,Midfielder,2551
210,Granit Xhaka,Arsenal,Midfielder,2502
282,Jonathan Hogg,Huddersfield Town,Midfielder,2377
260,Jean Michau00ebl Seri,Fulham,Midfielder,2252

In [44]:
players[["full_name","position","Current Club", "minutes_played_overall"]][(players["Current Club"]=="Manchester United") & (players.position=="Midfielder")]

             full_name    position       Current Club  minutes_played_overall
38       Ander Herrera  Midfielder  Manchester United                    1404
44     Andreas Pereira  Midfielder  Manchester United                     595
50         Angel Gomes  Midfielder  Manchester United                      25
65        Ashley Young  Midfielder  Manchester United                    2568
197               Fred  Midfielder  Manchester United                    1045
265      Jesse Lingard  Midfielder  Manchester United                    1668
303          Juan Mata  Midfielder  Manchester United                    1294
375  Marouane Fellaini  Midfielder  Manchester United                     744
379    Mason Greenwood  Midfielder  Manchester United                     115
427      Nemanja Matić  Midfielder  Manchester United                    2441
441         Paul Pogba  Midfielder  Manchester United                    3011
495    Scott McTominay  Midfielder  Manchester United                     861

In [45]:
mid2 = playerminutes[playerminutes["position"]=="Midfielder"]
mid2

,full_name,Current Club,position,minutes_played_overall
122,Conor Coady,Wolverhampton Wanderers,Midfielder,3420
354,Luka Milivojević,Crystal Palace,Midfielder,3420
234,Jack Cork,Burnley,Midfielder,3313
554,Wilfred Ndidi,Leicester City,Midfielder,3299
421,Nathan Redmond,Southampton,Midfielder,3276
...,...,...,...,...
213,Hamza Choudhury,Leicester City,Midfielder,596
44,Andreas Pereira,Manchester United,Midfielder,595
336,Leandro Bacuna,Cardiff City,Midfielder,554
413,Moussa Dembele,Tottenham Hotspur,Midfielder,516
546,Victor Wanyama,Tottenham Hotspur,Midfielder,509

In [46]:
# get only names not in mid 1
mid2 = mid2[~mid2.full_name.isin(mid1.full_name.values)]

In [47]:
#get only the next mid after first midfielder
mid2 = mid2.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
mid2

,full_name,Current Club,position,minutes_played_overall
5,Aaron Wan-Bissaka,Crystal Palace,Midfielder,3135
415,N'Golo Kanté,Chelsea,Midfielder,3096
266,João Moutinho,Wolverhampton Wanderers,Midfielder,3040
152,Declan Rice,West Ham United,Midfielder,3005
180,Étienne Capoue,Watford,Midfielder,2947
242,James Maddison,Leicester City,Midfielder,2850
227,Idrissa Gueye,Everton,Midfielder,2825
64,Ashley Westwood,Burnley,Midfielder,2822
454,Pierre-Emile Højbjerg,Southampton,Midfielder,2764
65,Ashley Young,Manchester United,Midfielder,2568
262,Jefferson Lerma,AFC Bournemouth,Midfielder,2511
127,Dale Stephens,Brighton & Hove Albion,Midfielder,2487
147,David Silva,Manchester City,Midfielder,2411
352,Lucas Torreira,Arsenal,Midfielder,2377
414,Moussa Sissoko,Tottenham Hotspur,Midfielder,2336
2,Aaron Mooy,Huddersfield Town,Midfielder,2327
60,Aron Einar Gunnarsson,Cardiff City,Midfielder,2274
531,Tom Cairney,Fulham,Midfielder,2198
407,Mohamed Diamé,Newcastle United,Midfielder,2165
184,Fabinho,Liverpool,Midfielder,2013

In [48]:
mid2

,full_name,Current Club,position,minutes_played_overall
5,Aaron Wan-Bissaka,Crystal Palace,Midfielder,3135
415,N'Golo Kanté,Chelsea,Midfielder,3096
266,João Moutinho,Wolverhampton Wanderers,Midfielder,3040
152,Declan Rice,West Ham United,Midfielder,3005
180,Étienne Capoue,Watford,Midfielder,2947
242,James Maddison,Leicester City,Midfielder,2850
227,Idrissa Gueye,Everton,Midfielder,2825
64,Ashley Westwood,Burnley,Midfielder,2822
454,Pierre-Emile Højbjerg,Southampton,Midfielder,2764
65,Ashley Young,Manchester United,Midfielder,2568
262,Jefferson Lerma,AFC Bournemouth,Midfielder,2511
127,Dale Stephens,Brighton & Hove Albion,Midfielder,2487
147,David Silva,Manchester City,Midfielder,2411
352,Lucas Torreira,Arsenal,Midfielder,2377
414,Moussa Sissoko,Tottenham Hotspur,Midfielder,2336
2,Aaron Mooy,Huddersfield Town,Midfielder,2327
60,Aron Einar Gunnarsson,Cardiff City,Midfielder,2274
531,Tom Cairney,Fulham,Midfielder,2198
407,Mohamed Diamé,Newcastle United,Midfielder,2165
184,Fabinho,Liverpool,Midfielder,2013

In [49]:
def1 = playerminutes[playerminutes["position"]=="Defender"]

In [50]:
#get only the first defender
def1 = def1.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
def1

,full_name,Current Club,position,minutes_played_overall
76,Ben Mee,Burnley,Defender,3420
419,Nathan Aké,AFC Bournemouth,Defender,3412
102,Cesar Azpilicueta,Chelsea,Defender,3403
550,Virgil van Dijk,Liverpool,Defender,3385
88,Bruno Écuélé Manga,Cardiff City,Defender,3375
117,Christopher Schindler,Huddersfield Town,Defender,3262
70,Ben Chilwell,Leicester City,Defender,3240
439,Patrick van Aanholt,Crystal Palace,Defender,3198
559,Willy Boly,Wolverhampton Wanderers,Defender,3169
345,Lewis Dunk,Brighton & Hove Albion,Defender,3153
124,Craig Cathcart,Watford,Defender,3099
67,Aymeric Laporte,Manchester City,Defender,3057
349,Lucas Digne,Everton,Defender,2990
232,Issa Diop,West Ham United,Defender,2970
530,Toby Alderweireld,Tottenham Hotspur,Defender,2924
240,Jamaal Lascelles,Newcastle United,Defender,2748
508,Shkodran Mustafi,Arsenal,Defender,2617
544,Victor Lindelöf,Manchester United,Defender,2602
157,Denis Odoi,Fulham,Defender,2593
480,Ryan Bertrand,Southampton,Defender,2160

In [51]:
def2 = playerminutes[playerminutes["position"]=="Defender"]

In [52]:
# get only names not in def 1
def2 = def2[~def2.full_name.isin(def1.full_name.values)]

In [53]:
#get only the next def after first defender
def2 = def2.sort_values(by="minutes_played_overall", ascending=False).drop_duplicates(
    subset="Current Club")
def2

,full_name,Current Club,position,minutes_played_overall
106,Charlie Taylor,Burnley,Defender,3240
146,David Luiz,Chelsea,Defender,3239
45,Andrew Robertson,Liverpool,Defender,3219
386,Matt Doherty,Wolverhampton Wanderers,Defender,3147
462,Ricardo Pereira,Leicester City,Defender,3125
505,Shane Duffy,Brighton & Hove Albion,Defender,3088
499,Sean Morrison,Cardiff City,Defender,3040
400,Michael Keane,Everton,Defender,2970
518,Steve Cook,AFC Bournemouth,Defender,2787
330,Kyle Walker,Manchester City,Defender,2777
525,Terence Kongolo,Huddersfield Town,Defender,2722
357,Luke Shaw,Manchester United,Defender,2592
96,Calum Chambers,Fulham,Defender,2587
247,James Tomkins,Crystal Palace,Defender,2563
151,DeAndre Yedlin,Newcastle United,Defender,2475
293,José Holebas,Watford,Defender,2394
324,Kieran Trippier,Tottenham Hotspur,Defender,2278
511,Sokratis Papastathopoulos,Arsenal,Defender,2199
251,Jan Bednarek,Southampton,Defender,2151
436,Pablo Zabaleta,West Ham United,Defender,2092

In [54]:
# merge all team names set
teamPlayers = pd.merge(teamPlayers, goalkeeper[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "gk"})
teamPlayers

               Current Club                           gk
0           AFC Bournemouth                Asmir Begović
1                   Arsenal                   Bernd Leno
2    Brighton & Hove Albion                  Mathew Ryan
3                   Burnley                   Tom Heaton
4              Cardiff City  Neil Leonard Dula Etheridge
5                   Chelsea            Kepa Arrizabalaga
6            Crystal Palace               Vicente Guaita
7                   Everton              Jordan Pickford
8                    Fulham                  Sergio Rico
9         Huddersfield Town                  Jonas Lössl
10           Leicester City            Kasper Schmeichel
11                Liverpool               Alisson Becker
12          Manchester City                      Ederson
13        Manchester United                 David de Gea
14         Newcastle United              Martin Dúbravka
15              Southampton                Alex McCarthy
16        Tottenham Hotspur                  Hugo Lloris
17                  Watford                   Ben Foster
18          West Ham United             Łukasz Fabiański
19  Wolverhampton Wanderers                 Rui Patrício

In [55]:
# merge all team names set
teamPlayers = pd.merge(teamPlayers, forward[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "fw"})
teamPlayers

,Current Club,gk,fw
0,AFC Bournemouth,Asmir Begović,Joshua King
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray
3,Burnley,Tom Heaton,Chris Wood
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett
5,Chelsea,Kepa Arrizabalaga,Willian
6,Crystal Palace,Vicente Guaita,Jordan Ayew
7,Everton,Jordan Pickford,Richarlison
8,Fulham,Sergio Rico,Aleksandar Mitrović
9,Huddersfield Town,Jonas Lössl,Steve Mounié
10,Leicester City,Kasper Schmeichel,Jamie Vardy
11,Liverpool,Alisson Becker,Mohamed Salah
12,Manchester City,Ederson,Raheem Sterling
13,Manchester United,David de Gea,Marcus Rashford
14,Newcastle United,Martin Dúbravka,Ayoze Perez
15,Southampton,Alex McCarthy,Danny Ings
16,Tottenham Hotspur,Hugo Lloris,Harry Kane
17,Watford,Ben Foster,Roberto Pereyra
18,West Ham United,Łukasz Fabiański,Marko Arnautović
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez

In [56]:
# merge midfields
teamPlayers = pd.merge(teamPlayers, mid1[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "md1"})
teamPlayers

,Current Club,gk,fw,md1
0,AFC Bournemouth,Asmir Begović,Joshua King,Ryan Fraser
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang,Granit Xhaka
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray,Davy Pröpper
3,Burnley,Tom Heaton,Chris Wood,Jack Cork
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett,Víctor Camarasa
5,Chelsea,Kepa Arrizabalaga,Willian,Jorginho
6,Crystal Palace,Vicente Guaita,Jordan Ayew,Luka Milivojević
7,Everton,Jordan Pickford,Richarlison,Gylfi Sigurdsson
8,Fulham,Sergio Rico,Aleksandar Mitrović,Jean Michau00ebl Seri
9,Huddersfield Town,Jonas Lössl,Steve Mounié,Jonathan Hogg
10,Leicester City,Kasper Schmeichel,Jamie Vardy,Wilfred Ndidi
11,Liverpool,Alisson Becker,Mohamed Salah,Georginio Wijnaldum
12,Manchester City,Ederson,Raheem Sterling,Bernardo Silva
13,Manchester United,David de Gea,Marcus Rashford,Paul Pogba
14,Newcastle United,Martin Dúbravka,Ayoze Perez,Matt Ritchie
15,Southampton,Alex McCarthy,Danny Ings,Nathan Redmond
16,Tottenham Hotspur,Hugo Lloris,Harry Kane,Christian Eriksen
17,Watford,Ben Foster,Roberto Pereyra,Abdoulaye Doucouré
18,West Ham United,Łukasz Fabiański,Marko Arnautović,Felipe Anderson
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez,Conor Coady

In [57]:
# merge midfields
teamPlayers = pd.merge(teamPlayers, mid2[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "md2"})
teamPlayers

,Current Club,gk,fw,md1,md2
0,AFC Bournemouth,Asmir Begović,Joshua King,Ryan Fraser,Jefferson Lerma
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang,Granit Xhaka,Lucas Torreira
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray,Davy Pröpper,Dale Stephens
3,Burnley,Tom Heaton,Chris Wood,Jack Cork,Ashley Westwood
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett,Víctor Camarasa,Aron Einar Gunnarsson
5,Chelsea,Kepa Arrizabalaga,Willian,Jorginho,N'Golo Kanté
6,Crystal Palace,Vicente Guaita,Jordan Ayew,Luka Milivojević,Aaron Wan-Bissaka
7,Everton,Jordan Pickford,Richarlison,Gylfi Sigurdsson,Idrissa Gueye
8,Fulham,Sergio Rico,Aleksandar Mitrović,Jean Michau00ebl Seri,Tom Cairney
9,Huddersfield Town,Jonas Lössl,Steve Mounié,Jonathan Hogg,Aaron Mooy
10,Leicester City,Kasper Schmeichel,Jamie Vardy,Wilfred Ndidi,James Maddison
11,Liverpool,Alisson Becker,Mohamed Salah,Georginio Wijnaldum,Fabinho
12,Manchester City,Ederson,Raheem Sterling,Bernardo Silva,David Silva
13,Manchester United,David de Gea,Marcus Rashford,Paul Pogba,Ashley Young
14,Newcastle United,Martin Dúbravka,Ayoze Perez,Matt Ritchie,Mohamed Diamé
15,Southampton,Alex McCarthy,Danny Ings,Nathan Redmond,Pierre-Emile Højbjerg
16,Tottenham Hotspur,Hugo Lloris,Harry Kane,Christian Eriksen,Moussa Sissoko
17,Watford,Ben Foster,Roberto Pereyra,Abdoulaye Doucouré,Étienne Capoue
18,West Ham United,Łukasz Fabiański,Marko Arnautović,Felipe Anderson,Declan Rice
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez,Conor Coady,João Moutinho

In [58]:
# merge defenders
teamPlayers = pd.merge(teamPlayers, def1[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "df1"})
teamPlayers

,Current Club,gk,fw,md1,md2,df1
0,AFC Bournemouth,Asmir Begović,Joshua King,Ryan Fraser,Jefferson Lerma,Nathan Aké
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang,Granit Xhaka,Lucas Torreira,Shkodran Mustafi
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray,Davy Pröpper,Dale Stephens,Lewis Dunk
3,Burnley,Tom Heaton,Chris Wood,Jack Cork,Ashley Westwood,Ben Mee
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett,Víctor Camarasa,Aron Einar Gunnarsson,Bruno Écuélé Manga
5,Chelsea,Kepa Arrizabalaga,Willian,Jorginho,N'Golo Kanté,Cesar Azpilicueta
6,Crystal Palace,Vicente Guaita,Jordan Ayew,Luka Milivojević,Aaron Wan-Bissaka,Patrick van Aanholt
7,Everton,Jordan Pickford,Richarlison,Gylfi Sigurdsson,Idrissa Gueye,Lucas Digne
8,Fulham,Sergio Rico,Aleksandar Mitrović,Jean Michau00ebl Seri,Tom Cairney,Denis Odoi
9,Huddersfield Town,Jonas Lössl,Steve Mounié,Jonathan Hogg,Aaron Mooy,Christopher Schindler
10,Leicester City,Kasper Schmeichel,Jamie Vardy,Wilfred Ndidi,James Maddison,Ben Chilwell
11,Liverpool,Alisson Becker,Mohamed Salah,Georginio Wijnaldum,Fabinho,Virgil van Dijk
12,Manchester City,Ederson,Raheem Sterling,Bernardo Silva,David Silva,Aymeric Laporte
13,Manchester United,David de Gea,Marcus Rashford,Paul Pogba,Ashley Young,Victor Lindelöf
14,Newcastle United,Martin Dúbravka,Ayoze Perez,Matt Ritchie,Mohamed Diamé,Jamaal Lascelles
15,Southampton,Alex McCarthy,Danny Ings,Nathan Redmond,Pierre-Emile Højbjerg,Ryan Bertrand
16,Tottenham Hotspur,Hugo Lloris,Harry Kane,Christian Eriksen,Moussa Sissoko,Toby Alderweireld
17,Watford,Ben Foster,Roberto Pereyra,Abdoulaye Doucouré,Étienne Capoue,Craig Cathcart
18,West Ham United,Łukasz Fabiański,Marko Arnautović,Felipe Anderson,Declan Rice,Issa Diop
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez,Conor Coady,João Moutinho,Willy Boly

In [59]:
# merge defenders
teamPlayers = pd.merge(teamPlayers, def2[["full_name","Current Club"]], how="left", on=["Current Club"]
                      ).rename(columns={"full_name": "df2"})
teamPlayers

,Current Club,gk,fw,md1,md2,df1,df2
0,AFC Bournemouth,Asmir Begović,Joshua King,Ryan Fraser,Jefferson Lerma,Nathan Aké,Steve Cook
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang,Granit Xhaka,Lucas Torreira,Shkodran Mustafi,Sokratis Papastathopoulos
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray,Davy Pröpper,Dale Stephens,Lewis Dunk,Shane Duffy
3,Burnley,Tom Heaton,Chris Wood,Jack Cork,Ashley Westwood,Ben Mee,Charlie Taylor
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett,Víctor Camarasa,Aron Einar Gunnarsson,Bruno Écuélé Manga,Sean Morrison
5,Chelsea,Kepa Arrizabalaga,Willian,Jorginho,N'Golo Kanté,Cesar Azpilicueta,David Luiz
6,Crystal Palace,Vicente Guaita,Jordan Ayew,Luka Milivojević,Aaron Wan-Bissaka,Patrick van Aanholt,James Tomkins
7,Everton,Jordan Pickford,Richarlison,Gylfi Sigurdsson,Idrissa Gueye,Lucas Digne,Michael Keane
8,Fulham,Sergio Rico,Aleksandar Mitrović,Jean Michau00ebl Seri,Tom Cairney,Denis Odoi,Calum Chambers
9,Huddersfield Town,Jonas Lössl,Steve Mounié,Jonathan Hogg,Aaron Mooy,Christopher Schindler,Terence Kongolo
10,Leicester City,Kasper Schmeichel,Jamie Vardy,Wilfred Ndidi,James Maddison,Ben Chilwell,Ricardo Pereira
11,Liverpool,Alisson Becker,Mohamed Salah,Georginio Wijnaldum,Fabinho,Virgil van Dijk,Andrew Robertson
12,Manchester City,Ederson,Raheem Sterling,Bernardo Silva,David Silva,Aymeric Laporte,Kyle Walker
13,Manchester United,David de Gea,Marcus Rashford,Paul Pogba,Ashley Young,Victor Lindelöf,Luke Shaw
14,Newcastle United,Martin Dúbravka,Ayoze Perez,Matt Ritchie,Mohamed Diamé,Jamaal Lascelles,DeAndre Yedlin
15,Southampton,Alex McCarthy,Danny Ings,Nathan Redmond,Pierre-Emile Højbjerg,Ryan Bertrand,Jan Bednarek
16,Tottenham Hotspur,Hugo Lloris,Harry Kane,Christian Eriksen,Moussa Sissoko,Toby Alderweireld,Kieran Trippier
17,Watford,Ben Foster,Roberto Pereyra,Abdoulaye Doucouré,Étienne Capoue,Craig Cathcart,José Holebas
18,West Ham United,Łukasz Fabiański,Marko Arnautović,Felipe Anderson,Declan Rice,Issa Diop,Pablo Zabaleta
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez,Conor Coady,João Moutinho,Willy Boly,Matt Doherty

In [135]:
teamPlayers.to_pickle("teams.pkl")

In [148]:
# get list of all player names
selectedNames = pd.concat([goalkeeper, forward, mid1, mid2, def1, def2])

In [150]:
selectedNames.to_pickle("selectedNames.pkl")

In [25]:
# load fifa22
p22= pd.read_csv("../data/players_22.csv")

/tmp/ipykernel_25856/1756297529.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  p22= pd.read_csv("../data/players_22.csv")

In [26]:
p22.columns.values

array(['sofifa_id', 'player_url', 'short_name', 'long_name',
       'player_positions', 'overall', 'potential', 'value_eur',
       'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id',
       'club_name', 'league_name', 'league_level', 'club_position',
       'club_jersey_number', 'club_loaned_from', 'club_joined',
       'club_contract_valid_until', 'nationality_id', 'nationality_name',
       'nation_team_id', 'nation_position', 'nation_jersey_number',
       'preferred_foot', 'weak_foot', 'skill_moves',
       'international_reputation', 'work_rate', 'body_type', 'real_face',
       'release_clause_eur', 'player_tags', 'player_traits', 'pace',
       'shooting', 'passing', 'dribbling', 'defending', 'physic',
       'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed',
       'movement_agility', 'movement_reactions', 'movement_balance',
       'power_shot_power', 'power_jumping', 'power_stamina',
       'power_strength', 'power_long_shots', 'mentality_aggression',
       'mentality_interceptions', 'mentality_positioning',
       'mentality_vision', 'mentality_penalties', 'mentality_composure',
       'defending_marking_awareness', 'defending_standing_tackle',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes',
       'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf',
       'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb',
       'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk',
       'player_face_url', 'club_logo_url', 'club_flag_url',
       'nation_logo_url', 'nation_flag_url'], dtype=object)

In [27]:
p22[["long_name", "club_name"]]

                                 long_name            club_name
0           Lionel Andrés Messi Cuccittini  Paris Saint-Germain
1                       Robert Lewandowski    FC Bayern München
2      Cristiano Ronaldo dos Santos Aveiro    Manchester United
3            Neymar da Silva Santos Júnior  Paris Saint-Germain
4                          Kevin De Bruyne      Manchester City
...                                    ...                  ...
19234                                  宋德福             Wuhan FC
19235                      Caoimhin Porter           Derry City
19236              Nathan Logue-Cunningham           Finn Harps
19237                          Luke Rudden           Finn Harps
19238              Emanuel Lalchhanchhuaha  NorthEast United FC

[19239 rows x 2 columns]

In [28]:
p22OK = p22[p22.club_name.isin(players["Current Club"].unique())]
p22OK.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/220002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruyne/220002,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png
9,202126,https://sofifa.com/player/202126/harry-kane/220002,H. Kane,Harry Kane,ST,90,90,129500000.0,240000.0,27,...,61+3,61+3,61+3,64+3,20+3,https://cdn.sofifa.net/players/202/126/22_120.png,https://cdn.sofifa.net/teams/18/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1318/60.png,https://cdn.sofifa.net/flags/gb-eng.png
10,215914,https://sofifa.com/player/215914/ngolo-kante/220002,N. Kanté,N'Golo Kanté,"CDM, CM",90,90,100000000.0,230000.0,30,...,84+3,84+3,84+3,85+3,20+3,https://cdn.sofifa.net/players/215/914/22_120.png,https://cdn.sofifa.net/teams/5/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1335/60.png,https://cdn.sofifa.net/flags/fr.png
13,200104,https://sofifa.com/player/200104/heung-min-son/220002,H. Son,손흥민 孙兴慜,"LM, CF, LW",89,89,104000000.0,220000.0,28,...,54+3,54+3,54+3,64+3,19+3,https://cdn.sofifa.net/players/200/104/22_120.png,https://cdn.sofifa.net/teams/18/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/kr.png

In [60]:
teamPlayers = pd.read_pickle("teams.pkl")

In [61]:
teamPlayers

,Current Club,gk,fw,md1,md2,df1,df2
0,AFC Bournemouth,Asmir Begović,Joshua King,Ryan Fraser,Jefferson Lerma,Nathan Aké,Steve Cook
1,Arsenal,Bernd Leno,Pierre-Emerick Aubameyang,Granit Xhaka,Lucas Torreira,Shkodran Mustafi,Sokratis Papastathopoulos
2,Brighton & Hove Albion,Mathew Ryan,Glenn Murray,Davy Pröpper,Dale Stephens,Lewis Dunk,Shane Duffy
3,Burnley,Tom Heaton,Chris Wood,Jack Cork,Ashley Westwood,Ben Mee,Charlie Taylor
4,Cardiff City,Neil Leonard Dula Etheridge,David Junior Hoilett,Víctor Camarasa,Aron Einar Gunnarsson,Bruno Écuélé Manga,Sean Morrison
5,Chelsea,Kepa Arrizabalaga,Willian,Jorginho,N'Golo Kanté,Cesar Azpilicueta,David Luiz
6,Crystal Palace,Vicente Guaita,Jordan Ayew,Luka Milivojević,Aaron Wan-Bissaka,Patrick van Aanholt,James Tomkins
7,Everton,Jordan Pickford,Richarlison,Gylfi Sigurdsson,Idrissa Gueye,Lucas Digne,Michael Keane
8,Fulham,Sergio Rico,Aleksandar Mitrović,Jean Michau00ebl Seri,Tom Cairney,Denis Odoi,Calum Chambers
9,Huddersfield Town,Jonas Lössl,Steve Mounié,Jonathan Hogg,Aaron Mooy,Christopher Schindler,Terence Kongolo
10,Leicester City,Kasper Schmeichel,Jamie Vardy,Wilfred Ndidi,James Maddison,Ben Chilwell,Ricardo Pereira
11,Liverpool,Alisson Becker,Mohamed Salah,Georginio Wijnaldum,Fabinho,Virgil van Dijk,Andrew Robertson
12,Manchester City,Ederson,Raheem Sterling,Bernardo Silva,David Silva,Aymeric Laporte,Kyle Walker
13,Manchester United,David de Gea,Marcus Rashford,Paul Pogba,Ashley Young,Victor Lindelöf,Luke Shaw
14,Newcastle United,Martin Dúbravka,Ayoze Perez,Matt Ritchie,Mohamed Diamé,Jamaal Lascelles,DeAndre Yedlin
15,Southampton,Alex McCarthy,Danny Ings,Nathan Redmond,Pierre-Emile Højbjerg,Ryan Bertrand,Jan Bednarek
16,Tottenham Hotspur,Hugo Lloris,Harry Kane,Christian Eriksen,Moussa Sissoko,Toby Alderweireld,Kieran Trippier
17,Watford,Ben Foster,Roberto Pereyra,Abdoulaye Doucouré,Étienne Capoue,Craig Cathcart,José Holebas
18,West Ham United,Łukasz Fabiański,Marko Arnautović,Felipe Anderson,Declan Rice,Issa Diop,Pablo Zabaleta
19,Wolverhampton Wanderers,Rui Patrício,Raúl Jiménez,Conor Coady,João Moutinho,Willy Boly,Matt Doherty

In [62]:
selectedNames = pd.read_pickle("selectedNames.pkl")

In [70]:
selectedNames

,full_name,Current Club,position,minutes_played_overall
569,Łukasz Fabiański,West Ham United,Goalkeeper,3420
426,Neil Leonard Dula Etheridge,Cardiff City,Goalkeeper,3420
144,David de Gea,Manchester United,Goalkeeper,3420
36,Alisson Becker,Liverpool,Goalkeeper,3420
290,Jordan Pickford,Everton,Goalkeeper,3420
...,...,...,...,...
293,José Holebas,Watford,Defender,2394
324,Kieran Trippier,Tottenham Hotspur,Defender,2278
511,Sokratis Papastathopoulos,Arsenal,Defender,2199
251,Jan Bednarek,Southampton,Defender,2151
436,Pablo Zabaleta,West Ham United,Defender,2092

In [66]:
pd.merge(selectedNames[["full_name"]], p22OK[["long_name","player_url","short_name"]], 
         how="left", left_on="full_name", right_on="long_name")

,full_name,long_name,player_url,short_name
0,Łukasz Fabiański,Łukasz Fabiański,https://sofifa.com/player/164835/lukasz-fabianski/220002,Ł. Fabiański
1,Neil Leonard Dula Etheridge,NaN,NaN,NaN
2,David de Gea,NaN,NaN,NaN
3,Alisson Becker,NaN,NaN,NaN
4,Jordan Pickford,Jordan Pickford,https://sofifa.com/player/204935/jordan-pickford/220002,J. Pickford
...,...,...,...,...
115,José Holebas,NaN,NaN,NaN
116,Kieran Trippier,NaN,NaN,NaN
117,Sokratis Papastathopoulos,NaN,NaN,NaN
118,Jan Bednarek,Jan Bednarek,https://sofifa.com/player/220570/jan-bednarek/220002,J. Bednarek
119,Pablo Zabaleta,NaN,NaN,NaN

In [ ]:
p22OK[["long_name","player_url","short_name"]][p22OK.long_name]

In [78]:
p22OK[["long_name","player_url","short_name","club_name"]][p22OK.long_name.str.contains("David")]

,long_name,player_url,short_name,club_name
106,David De Gea Quintana,https://sofifa.com/player/193080/david-de-gea-quintana/220002,De Gea,Manchester United
310,James David Rodríguez Rubio,https://sofifa.com/player/198710/james-rodriguez/220002,J. Rodríguez,Everton
1316,David Robert Brooks,https://sofifa.com/player/220196/david-brooks/220002,D. Brooks,AFC Bournemouth
1508,Adam David Lallana,https://sofifa.com/player/180819/adam-lallana/220002,A. Lallana,Brighton & Hove Albion
9808,David Edward Martin,https://sofifa.com/player/116314/david-martin/220002,D. Martin,West Ham United
10920,Anthony David Junior Elanga,https://sofifa.com/player/257470/anthony-elanga/220002,A. Elanga,Manchester United
13905,Harvey David White,https://sofifa.com/player/245903/harvey-white/220002,H. White,Tottenham Hotspur

In [83]:
list(np.sort(p22OK.club_name.unique()))

['AFC Bournemouth',
 'Arsenal',
 'Brighton & Hove Albion',
 'Burnley',
 'Cardiff City',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield Town',
 'Leicester City',
 'Liverpool',
 'Manchester City',
 'Manchester United',
 'Newcastle United',
 'Southampton',
 'Tottenham Hotspur',
 'Watford',
 'West Ham United',
 'Wolverhampton Wanderers']

In [85]:
list(np.sort(selectedNames["Current Club"].unique()))

['AFC Bournemouth',
 'Arsenal',
 'Brighton & Hove Albion',
 'Burnley',
 'Cardiff City',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield Town',
 'Leicester City',
 'Liverpool',
 'Manchester City',
 'Manchester United',
 'Newcastle United',
 'Southampton',
 'Tottenham Hotspur',
 'Watford',
 'West Ham United',
 'Wolverhampton Wanderers']

In [87]:
p22OK.columns.values

array(['sofifa_id', 'player_url', 'short_name', 'long_name',
       'player_positions', 'overall', 'potential', 'value_eur',
       'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id',
       'club_name', 'league_name', 'league_level', 'club_position',
       'club_jersey_number', 'club_loaned_from', 'club_joined',
       'club_contract_valid_until', 'nationality_id', 'nationality_name',
       'nation_team_id', 'nation_position', 'nation_jersey_number',
       'preferred_foot', 'weak_foot', 'skill_moves',
       'international_reputation', 'work_rate', 'body_type', 'real_face',
       'release_clause_eur', 'player_tags', 'player_traits', 'pace',
       'shooting', 'passing', 'dribbling', 'defending', 'physic',
       'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed',
       'movement_agility', 'movement_reactions', 'movement_balance',
       'power_shot_power', 'power_jumping', 'power_stamina',
       'power_strength', 'power_long_shots', 'mentality_aggression',
       'mentality_interceptions', 'mentality_positioning',
       'mentality_vision', 'mentality_penalties', 'mentality_composure',
       'defending_marking_awareness', 'defending_standing_tackle',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes',
       'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf',
       'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb',
       'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk',
       'player_face_url', 'club_logo_url', 'club_flag_url',
       'nation_logo_url', 'nation_flag_url'], dtype=object)

In [92]:
p22OK["club_position"].unique()

array(['ST', 'RCM', 'LW', 'LCB', 'RW', 'GK', 'SUB', 'CAM', 'RDM', 'LB',
       'RB', 'LM', 'RCB', 'LCM', 'CDM', 'CF', 'LDM', 'RWB', 'RM', 'CB',
       'RES', 'RS', 'LWB', 'LS', 'CM'], dtype=object)

In [94]:
p22OK[['short_name', 'long_name','player_positions', 'overall', 'potential', 'value_eur',
       'wage_eur']]

,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur
2,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0
4,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0
9,H. Kane,Harry Kane,ST,90,90,129500000.0,240000.0
10,N. Kanté,N'Golo Kanté,"CDM, CM",90,90,100000000.0,230000.0
13,H. Son,손흥민 孙兴慜,"LM, CF, LW",89,89,104000000.0,220000.0
...,...,...,...,...,...,...,...
18692,O. Ashley,Ossama Ashley,CM,52,64,200000.0,6000.0
18743,B. Camp,Brennan Camp,"CB, RB",52,68,200000.0,3000.0
18854,N. Moriah-Welsh,Nathan Moriah-Welsh,CM,52,65,190000.0,3000.0
18877,P. Estrada,Pascal Juan Estrada,"CB, CM",51,65,130000.0,5000.0
18878,O. Webber,Oliver Webber,GK,51,64,130000.0,3000.0